[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
zkin_smartwallet = "3CT4tE6xNnhpPgvXhXRnK2qZooXxvwRqrJMuVdFXVjeY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/ppoliani/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
