[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
zkin_smartwallet = "zkinKSHW3PijK2ZyRDUSXe8m2UKnNjJPvnv2NeZUvHy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/ppoliani/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
