[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
zkin_smartwallet = "zkinKSHW3PijK2ZyRDUSXe8m2UKnNjJPvnv2NeZUvHy"

[programs.mainnet]
zkin_smartwallet = "zkinKSHW3PijK2ZyRDUSXe8m2UKnNjJPvnv2NeZUvHy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./wallets/deployer.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/**/*.js"
